// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type AppSettingsData struct {
	CompanyName string
	LogoURL     string
	Errors      map[string]string
	Success     string
}

func AppSettingsContent(data AppSettingsData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"max-width: 640px;\"><!-- Page Title --><div style=\"margin-bottom: 40px;\"><h1 style=\"font-family: 'Space Grotesk', sans-serif; font-size: 24px; font-weight: 600; color: var(--text-primary); letter-spacing: 0.02em; text-transform: uppercase;\">GLOBAL SETTINGS</h1><p style=\"font-family: 'Inter', sans-serif; font-size: 13px; color: var(--text-secondary); margin-top: 8px;\">Company branding used in the application header and PDF exports.</p></div><form method=\"POST\" action=\"/settings\" enctype=\"multipart/form-data\" hx-post=\"/settings\" hx-encoding=\"multipart/form-data\" hx-target=\"#main-content\" x-data=\"{\n\t\t\t\tpreviewURL: '',\n\t\t\t\tremoveLogo: false,\n\t\t\t\thandleFile(event) {\n\t\t\t\t\tconst file = event.target.files[0];\n\t\t\t\t\tif (file) {\n\t\t\t\t\t\tthis.previewURL = URL.createObjectURL(file);\n\t\t\t\t\t\tthis.removeLogo = false;\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\tclearLogo() {\n\t\t\t\t\tthis.removeLogo = true;\n\t\t\t\t\tthis.previewURL = '';\n\t\t\t\t\tdocument.getElementById('logo-input').value = '';\n\t\t\t\t}\n\t\t\t}\"><!-- Logo Section --><div style=\"padding: 32px; margin-bottom: 24px; background-color: var(--bg-card);\"><label style=\"display: block; font-family: 'Space Grotesk', sans-serif; font-size: 11px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; color: var(--text-secondary); margin-bottom: 16px;\">COMPANY LOGO</label><!-- Current Logo Preview --><div style=\"margin-bottom: 20px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.LogoURL != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div x-show=\"!removeLogo && !previewURL\"><img src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.LogoURL)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/app_settings.templ`, Line: 57, Col: 26}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" alt=\"Company Logo\" style=\"max-height: 64px; max-width: 240px; object-fit: contain;\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- New file preview --><div x-show=\"previewURL\" x-cloak><img :src=\"previewURL\" alt=\"Logo preview\" style=\"max-height: 64px; max-width: 240px; object-fit: contain;\"></div><!-- No logo placeholder -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.LogoURL == "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div x-show=\"!previewURL\" style=\"width: 120px; height: 64px; display: flex; align-items: center; justify-content: center; border: 2px dashed var(--border-light);\"><span style=\"font-family: 'Inter', sans-serif; font-size: 11px; color: var(--text-muted);\">No logo</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><!-- Upload / Remove Buttons --><div style=\"display: flex; gap: 12px; align-items: center;\"><label for=\"logo-input\" style=\"display: inline-block; padding: 8px 20px; cursor: pointer; font-family: 'Space Grotesk', sans-serif; font-size: 11px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; color: white; background-color: var(--terracotta);\">UPLOAD LOGO</label> <input type=\"file\" id=\"logo-input\" name=\"logo\" accept=\"image/png,image/jpeg,image/svg+xml,image/webp\" @change=\"handleFile($event)\" style=\"display: none;\"> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.LogoURL != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<button type=\"button\" @click=\"clearLogo()\" style=\"padding: 8px 20px; cursor: pointer; font-family: 'Space Grotesk', sans-serif; font-size: 11px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; color: var(--error); background: none; border: 1px solid var(--error);\">REMOVE</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><input type=\"hidden\" name=\"remove_logo\" :value=\"removeLogo ? 'true' : 'false'\"><p style=\"font-family: 'Inter', sans-serif; font-size: 11px; color: var(--text-muted); margin-top: 12px;\">PNG, JPEG, SVG, or WebP. Max 2 MB. Recommended height: 40–80px.</p></div><!-- Company Name Section --><div style=\"padding: 32px; margin-bottom: 24px; background-color: var(--bg-card);\"><label for=\"company_name\" style=\"display: block; font-family: 'Space Grotesk', sans-serif; font-size: 11px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; color: var(--text-secondary); margin-bottom: 8px;\">COMPANY NAME</label> <input type=\"text\" id=\"company_name\" name=\"company_name\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.CompanyName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/app_settings.templ`, Line: 125, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("width: 100%; padding: 10px 12px; font-family: 'Inter', sans-serif; font-size: 14px; color: var(--text-primary); background-color: white; border: 1px solid " + inputBorderColor(data.Errors["company_name"]) + ";")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/app_settings.templ`, Line: 126, Col: 224}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\"> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.Errors["company_name"] != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<p style=\"font-family: 'Inter', sans-serif; font-size: 12px; color: var(--error); margin-top: 6px;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.Errors["company_name"])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/app_settings.templ`, Line: 130, Col: 35}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<p style=\"font-family: 'Inter', sans-serif; font-size: 11px; color: var(--text-muted); margin-top: 8px;\">Used in the header and as the company name on PDF exports.</p></div><!-- Save Button --><div style=\"display: flex; justify-content: flex-end;\"><button type=\"submit\" style=\"padding: 10px 32px; cursor: pointer; font-family: 'Space Grotesk', sans-serif; font-size: 12px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; color: white; background-color: var(--terracotta); border: none;\">SAVE SETTINGS</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func AppSettingsPage(data AppSettingsData, headerData HeaderData, sidebarData SidebarData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var7 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = AppSettingsContent(data).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = PageShellWithProject("Global Settings", headerData, sidebarData).Render(templ.WithChildren(ctx, templ_7745c5c3_Var7), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func inputBorderColor(errMsg string) string {
	if errMsg != "" {
		return "var(--error)"
	}
	return "var(--border-light)"
}

var _ = templruntime.GeneratedTemplate
